require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ConductorsController do

  # This should return the minimal set of attributes required to create a valid
  # Conductor. As you add validations to Conductor, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConductorsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all conductors as @conductors" do
      conductor = Conductor.create! valid_attributes
      get :index, {}, valid_session
      assigns(:conductors).should eq([conductor])
    end
  end

  describe "GET show" do
    it "assigns the requested conductor as @conductor" do
      conductor = Conductor.create! valid_attributes
      get :show, {:id => conductor.to_param}, valid_session
      assigns(:conductor).should eq(conductor)
    end
  end

  describe "GET new" do
    it "assigns a new conductor as @conductor" do
      get :new, {}, valid_session
      assigns(:conductor).should be_a_new(Conductor)
    end
  end

  describe "GET edit" do
    it "assigns the requested conductor as @conductor" do
      conductor = Conductor.create! valid_attributes
      get :edit, {:id => conductor.to_param}, valid_session
      assigns(:conductor).should eq(conductor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Conductor" do
        expect {
          post :create, {:conductor => valid_attributes}, valid_session
        }.to change(Conductor, :count).by(1)
      end

      it "assigns a newly created conductor as @conductor" do
        post :create, {:conductor => valid_attributes}, valid_session
        assigns(:conductor).should be_a(Conductor)
        assigns(:conductor).should be_persisted
      end

      it "redirects to the created conductor" do
        post :create, {:conductor => valid_attributes}, valid_session
        response.should redirect_to(Conductor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved conductor as @conductor" do
        # Trigger the behavior that occurs when invalid params are submitted
        Conductor.any_instance.stub(:save).and_return(false)
        post :create, {:conductor => {}}, valid_session
        assigns(:conductor).should be_a_new(Conductor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Conductor.any_instance.stub(:save).and_return(false)
        post :create, {:conductor => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested conductor" do
        conductor = Conductor.create! valid_attributes
        # Assuming there are no other conductors in the database, this
        # specifies that the Conductor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Conductor.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => conductor.to_param, :conductor => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested conductor as @conductor" do
        conductor = Conductor.create! valid_attributes
        put :update, {:id => conductor.to_param, :conductor => valid_attributes}, valid_session
        assigns(:conductor).should eq(conductor)
      end

      it "redirects to the conductor" do
        conductor = Conductor.create! valid_attributes
        put :update, {:id => conductor.to_param, :conductor => valid_attributes}, valid_session
        response.should redirect_to(conductor)
      end
    end

    describe "with invalid params" do
      it "assigns the conductor as @conductor" do
        conductor = Conductor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Conductor.any_instance.stub(:save).and_return(false)
        put :update, {:id => conductor.to_param, :conductor => {}}, valid_session
        assigns(:conductor).should eq(conductor)
      end

      it "re-renders the 'edit' template" do
        conductor = Conductor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Conductor.any_instance.stub(:save).and_return(false)
        put :update, {:id => conductor.to_param, :conductor => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested conductor" do
      conductor = Conductor.create! valid_attributes
      expect {
        delete :destroy, {:id => conductor.to_param}, valid_session
      }.to change(Conductor, :count).by(-1)
    end

    it "redirects to the conductors list" do
      conductor = Conductor.create! valid_attributes
      delete :destroy, {:id => conductor.to_param}, valid_session
      response.should redirect_to(conductors_url)
    end
  end

end
