require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MedallasController do

  # This should return the minimal set of attributes required to create a valid
  # Medalla. As you add validations to Medalla, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MedallasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all medallas as @medallas" do
      medalla = Medalla.create! valid_attributes
      get :index, {}, valid_session
      assigns(:medallas).should eq([medalla])
    end
  end

  describe "GET show" do
    it "assigns the requested medalla as @medalla" do
      medalla = Medalla.create! valid_attributes
      get :show, {:id => medalla.to_param}, valid_session
      assigns(:medalla).should eq(medalla)
    end
  end

  describe "GET new" do
    it "assigns a new medalla as @medalla" do
      get :new, {}, valid_session
      assigns(:medalla).should be_a_new(Medalla)
    end
  end

  describe "GET edit" do
    it "assigns the requested medalla as @medalla" do
      medalla = Medalla.create! valid_attributes
      get :edit, {:id => medalla.to_param}, valid_session
      assigns(:medalla).should eq(medalla)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Medalla" do
        expect {
          post :create, {:medalla => valid_attributes}, valid_session
        }.to change(Medalla, :count).by(1)
      end

      it "assigns a newly created medalla as @medalla" do
        post :create, {:medalla => valid_attributes}, valid_session
        assigns(:medalla).should be_a(Medalla)
        assigns(:medalla).should be_persisted
      end

      it "redirects to the created medalla" do
        post :create, {:medalla => valid_attributes}, valid_session
        response.should redirect_to(Medalla.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved medalla as @medalla" do
        # Trigger the behavior that occurs when invalid params are submitted
        Medalla.any_instance.stub(:save).and_return(false)
        post :create, {:medalla => {}}, valid_session
        assigns(:medalla).should be_a_new(Medalla)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Medalla.any_instance.stub(:save).and_return(false)
        post :create, {:medalla => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested medalla" do
        medalla = Medalla.create! valid_attributes
        # Assuming there are no other medallas in the database, this
        # specifies that the Medalla created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Medalla.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => medalla.to_param, :medalla => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested medalla as @medalla" do
        medalla = Medalla.create! valid_attributes
        put :update, {:id => medalla.to_param, :medalla => valid_attributes}, valid_session
        assigns(:medalla).should eq(medalla)
      end

      it "redirects to the medalla" do
        medalla = Medalla.create! valid_attributes
        put :update, {:id => medalla.to_param, :medalla => valid_attributes}, valid_session
        response.should redirect_to(medalla)
      end
    end

    describe "with invalid params" do
      it "assigns the medalla as @medalla" do
        medalla = Medalla.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Medalla.any_instance.stub(:save).and_return(false)
        put :update, {:id => medalla.to_param, :medalla => {}}, valid_session
        assigns(:medalla).should eq(medalla)
      end

      it "re-renders the 'edit' template" do
        medalla = Medalla.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Medalla.any_instance.stub(:save).and_return(false)
        put :update, {:id => medalla.to_param, :medalla => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested medalla" do
      medalla = Medalla.create! valid_attributes
      expect {
        delete :destroy, {:id => medalla.to_param}, valid_session
      }.to change(Medalla, :count).by(-1)
    end

    it "redirects to the medallas list" do
      medalla = Medalla.create! valid_attributes
      delete :destroy, {:id => medalla.to_param}, valid_session
      response.should redirect_to(medallas_url)
    end
  end

end
