require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReportesController do

  # This should return the minimal set of attributes required to create a valid
  # Reporte. As you add validations to Reporte, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReportesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all reportes as @reportes" do
      reporte = Reporte.create! valid_attributes
      get :index, {}, valid_session
      assigns(:reportes).should eq([reporte])
    end
  end

  describe "GET show" do
    it "assigns the requested reporte as @reporte" do
      reporte = Reporte.create! valid_attributes
      get :show, {:id => reporte.to_param}, valid_session
      assigns(:reporte).should eq(reporte)
    end
  end

  describe "GET new" do
    it "assigns a new reporte as @reporte" do
      get :new, {}, valid_session
      assigns(:reporte).should be_a_new(Reporte)
    end
  end

  describe "GET edit" do
    it "assigns the requested reporte as @reporte" do
      reporte = Reporte.create! valid_attributes
      get :edit, {:id => reporte.to_param}, valid_session
      assigns(:reporte).should eq(reporte)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Reporte" do
        expect {
          post :create, {:reporte => valid_attributes}, valid_session
        }.to change(Reporte, :count).by(1)
      end

      it "assigns a newly created reporte as @reporte" do
        post :create, {:reporte => valid_attributes}, valid_session
        assigns(:reporte).should be_a(Reporte)
        assigns(:reporte).should be_persisted
      end

      it "redirects to the created reporte" do
        post :create, {:reporte => valid_attributes}, valid_session
        response.should redirect_to(Reporte.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reporte as @reporte" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reporte.any_instance.stub(:save).and_return(false)
        post :create, {:reporte => {}}, valid_session
        assigns(:reporte).should be_a_new(Reporte)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reporte.any_instance.stub(:save).and_return(false)
        post :create, {:reporte => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reporte" do
        reporte = Reporte.create! valid_attributes
        # Assuming there are no other reportes in the database, this
        # specifies that the Reporte created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Reporte.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => reporte.to_param, :reporte => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested reporte as @reporte" do
        reporte = Reporte.create! valid_attributes
        put :update, {:id => reporte.to_param, :reporte => valid_attributes}, valid_session
        assigns(:reporte).should eq(reporte)
      end

      it "redirects to the reporte" do
        reporte = Reporte.create! valid_attributes
        put :update, {:id => reporte.to_param, :reporte => valid_attributes}, valid_session
        response.should redirect_to(reporte)
      end
    end

    describe "with invalid params" do
      it "assigns the reporte as @reporte" do
        reporte = Reporte.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reporte.any_instance.stub(:save).and_return(false)
        put :update, {:id => reporte.to_param, :reporte => {}}, valid_session
        assigns(:reporte).should eq(reporte)
      end

      it "re-renders the 'edit' template" do
        reporte = Reporte.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reporte.any_instance.stub(:save).and_return(false)
        put :update, {:id => reporte.to_param, :reporte => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reporte" do
      reporte = Reporte.create! valid_attributes
      expect {
        delete :destroy, {:id => reporte.to_param}, valid_session
      }.to change(Reporte, :count).by(-1)
    end

    it "redirects to the reportes list" do
      reporte = Reporte.create! valid_attributes
      delete :destroy, {:id => reporte.to_param}, valid_session
      response.should redirect_to(reportes_url)
    end
  end

end
