require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReservacionsController do

  # This should return the minimal set of attributes required to create a valid
  # Reservacion. As you add validations to Reservacion, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReservacionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all reservacions as @reservacions" do
      reservacion = Reservacion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:reservacions).should eq([reservacion])
    end
  end

  describe "GET show" do
    it "assigns the requested reservacion as @reservacion" do
      reservacion = Reservacion.create! valid_attributes
      get :show, {:id => reservacion.to_param}, valid_session
      assigns(:reservacion).should eq(reservacion)
    end
  end

  describe "GET new" do
    it "assigns a new reservacion as @reservacion" do
      get :new, {}, valid_session
      assigns(:reservacion).should be_a_new(Reservacion)
    end
  end

  describe "GET edit" do
    it "assigns the requested reservacion as @reservacion" do
      reservacion = Reservacion.create! valid_attributes
      get :edit, {:id => reservacion.to_param}, valid_session
      assigns(:reservacion).should eq(reservacion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Reservacion" do
        expect {
          post :create, {:reservacion => valid_attributes}, valid_session
        }.to change(Reservacion, :count).by(1)
      end

      it "assigns a newly created reservacion as @reservacion" do
        post :create, {:reservacion => valid_attributes}, valid_session
        assigns(:reservacion).should be_a(Reservacion)
        assigns(:reservacion).should be_persisted
      end

      it "redirects to the created reservacion" do
        post :create, {:reservacion => valid_attributes}, valid_session
        response.should redirect_to(Reservacion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reservacion as @reservacion" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reservacion.any_instance.stub(:save).and_return(false)
        post :create, {:reservacion => {}}, valid_session
        assigns(:reservacion).should be_a_new(Reservacion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reservacion.any_instance.stub(:save).and_return(false)
        post :create, {:reservacion => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reservacion" do
        reservacion = Reservacion.create! valid_attributes
        # Assuming there are no other reservacions in the database, this
        # specifies that the Reservacion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Reservacion.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => reservacion.to_param, :reservacion => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested reservacion as @reservacion" do
        reservacion = Reservacion.create! valid_attributes
        put :update, {:id => reservacion.to_param, :reservacion => valid_attributes}, valid_session
        assigns(:reservacion).should eq(reservacion)
      end

      it "redirects to the reservacion" do
        reservacion = Reservacion.create! valid_attributes
        put :update, {:id => reservacion.to_param, :reservacion => valid_attributes}, valid_session
        response.should redirect_to(reservacion)
      end
    end

    describe "with invalid params" do
      it "assigns the reservacion as @reservacion" do
        reservacion = Reservacion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reservacion.any_instance.stub(:save).and_return(false)
        put :update, {:id => reservacion.to_param, :reservacion => {}}, valid_session
        assigns(:reservacion).should eq(reservacion)
      end

      it "re-renders the 'edit' template" do
        reservacion = Reservacion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reservacion.any_instance.stub(:save).and_return(false)
        put :update, {:id => reservacion.to_param, :reservacion => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reservacion" do
      reservacion = Reservacion.create! valid_attributes
      expect {
        delete :destroy, {:id => reservacion.to_param}, valid_session
      }.to change(Reservacion, :count).by(-1)
    end

    it "redirects to the reservacions list" do
      reservacion = Reservacion.create! valid_attributes
      delete :destroy, {:id => reservacion.to_param}, valid_session
      response.should redirect_to(reservacions_url)
    end
  end

end
