require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RetroalimentacionsController do

  # This should return the minimal set of attributes required to create a valid
  # Retroalimentacion. As you add validations to Retroalimentacion, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RetroalimentacionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all retroalimentacions as @retroalimentacions" do
      retroalimentacion = Retroalimentacion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:retroalimentacions).should eq([retroalimentacion])
    end
  end

  describe "GET show" do
    it "assigns the requested retroalimentacion as @retroalimentacion" do
      retroalimentacion = Retroalimentacion.create! valid_attributes
      get :show, {:id => retroalimentacion.to_param}, valid_session
      assigns(:retroalimentacion).should eq(retroalimentacion)
    end
  end

  describe "GET new" do
    it "assigns a new retroalimentacion as @retroalimentacion" do
      get :new, {}, valid_session
      assigns(:retroalimentacion).should be_a_new(Retroalimentacion)
    end
  end

  describe "GET edit" do
    it "assigns the requested retroalimentacion as @retroalimentacion" do
      retroalimentacion = Retroalimentacion.create! valid_attributes
      get :edit, {:id => retroalimentacion.to_param}, valid_session
      assigns(:retroalimentacion).should eq(retroalimentacion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Retroalimentacion" do
        expect {
          post :create, {:retroalimentacion => valid_attributes}, valid_session
        }.to change(Retroalimentacion, :count).by(1)
      end

      it "assigns a newly created retroalimentacion as @retroalimentacion" do
        post :create, {:retroalimentacion => valid_attributes}, valid_session
        assigns(:retroalimentacion).should be_a(Retroalimentacion)
        assigns(:retroalimentacion).should be_persisted
      end

      it "redirects to the created retroalimentacion" do
        post :create, {:retroalimentacion => valid_attributes}, valid_session
        response.should redirect_to(Retroalimentacion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved retroalimentacion as @retroalimentacion" do
        # Trigger the behavior that occurs when invalid params are submitted
        Retroalimentacion.any_instance.stub(:save).and_return(false)
        post :create, {:retroalimentacion => {}}, valid_session
        assigns(:retroalimentacion).should be_a_new(Retroalimentacion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Retroalimentacion.any_instance.stub(:save).and_return(false)
        post :create, {:retroalimentacion => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested retroalimentacion" do
        retroalimentacion = Retroalimentacion.create! valid_attributes
        # Assuming there are no other retroalimentacions in the database, this
        # specifies that the Retroalimentacion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Retroalimentacion.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => retroalimentacion.to_param, :retroalimentacion => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested retroalimentacion as @retroalimentacion" do
        retroalimentacion = Retroalimentacion.create! valid_attributes
        put :update, {:id => retroalimentacion.to_param, :retroalimentacion => valid_attributes}, valid_session
        assigns(:retroalimentacion).should eq(retroalimentacion)
      end

      it "redirects to the retroalimentacion" do
        retroalimentacion = Retroalimentacion.create! valid_attributes
        put :update, {:id => retroalimentacion.to_param, :retroalimentacion => valid_attributes}, valid_session
        response.should redirect_to(retroalimentacion)
      end
    end

    describe "with invalid params" do
      it "assigns the retroalimentacion as @retroalimentacion" do
        retroalimentacion = Retroalimentacion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Retroalimentacion.any_instance.stub(:save).and_return(false)
        put :update, {:id => retroalimentacion.to_param, :retroalimentacion => {}}, valid_session
        assigns(:retroalimentacion).should eq(retroalimentacion)
      end

      it "re-renders the 'edit' template" do
        retroalimentacion = Retroalimentacion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Retroalimentacion.any_instance.stub(:save).and_return(false)
        put :update, {:id => retroalimentacion.to_param, :retroalimentacion => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested retroalimentacion" do
      retroalimentacion = Retroalimentacion.create! valid_attributes
      expect {
        delete :destroy, {:id => retroalimentacion.to_param}, valid_session
      }.to change(Retroalimentacion, :count).by(-1)
    end

    it "redirects to the retroalimentacions list" do
      retroalimentacion = Retroalimentacion.create! valid_attributes
      delete :destroy, {:id => retroalimentacion.to_param}, valid_session
      response.should redirect_to(retroalimentacions_url)
    end
  end

end
