require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TipomedallasController do

  # This should return the minimal set of attributes required to create a valid
  # Tipomedalla. As you add validations to Tipomedalla, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TipomedallasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tipomedallas as @tipomedallas" do
      tipomedalla = Tipomedalla.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tipomedallas).should eq([tipomedalla])
    end
  end

  describe "GET show" do
    it "assigns the requested tipomedalla as @tipomedalla" do
      tipomedalla = Tipomedalla.create! valid_attributes
      get :show, {:id => tipomedalla.to_param}, valid_session
      assigns(:tipomedalla).should eq(tipomedalla)
    end
  end

  describe "GET new" do
    it "assigns a new tipomedalla as @tipomedalla" do
      get :new, {}, valid_session
      assigns(:tipomedalla).should be_a_new(Tipomedalla)
    end
  end

  describe "GET edit" do
    it "assigns the requested tipomedalla as @tipomedalla" do
      tipomedalla = Tipomedalla.create! valid_attributes
      get :edit, {:id => tipomedalla.to_param}, valid_session
      assigns(:tipomedalla).should eq(tipomedalla)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tipomedalla" do
        expect {
          post :create, {:tipomedalla => valid_attributes}, valid_session
        }.to change(Tipomedalla, :count).by(1)
      end

      it "assigns a newly created tipomedalla as @tipomedalla" do
        post :create, {:tipomedalla => valid_attributes}, valid_session
        assigns(:tipomedalla).should be_a(Tipomedalla)
        assigns(:tipomedalla).should be_persisted
      end

      it "redirects to the created tipomedalla" do
        post :create, {:tipomedalla => valid_attributes}, valid_session
        response.should redirect_to(Tipomedalla.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tipomedalla as @tipomedalla" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tipomedalla.any_instance.stub(:save).and_return(false)
        post :create, {:tipomedalla => {}}, valid_session
        assigns(:tipomedalla).should be_a_new(Tipomedalla)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tipomedalla.any_instance.stub(:save).and_return(false)
        post :create, {:tipomedalla => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tipomedalla" do
        tipomedalla = Tipomedalla.create! valid_attributes
        # Assuming there are no other tipomedallas in the database, this
        # specifies that the Tipomedalla created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tipomedalla.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tipomedalla.to_param, :tipomedalla => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tipomedalla as @tipomedalla" do
        tipomedalla = Tipomedalla.create! valid_attributes
        put :update, {:id => tipomedalla.to_param, :tipomedalla => valid_attributes}, valid_session
        assigns(:tipomedalla).should eq(tipomedalla)
      end

      it "redirects to the tipomedalla" do
        tipomedalla = Tipomedalla.create! valid_attributes
        put :update, {:id => tipomedalla.to_param, :tipomedalla => valid_attributes}, valid_session
        response.should redirect_to(tipomedalla)
      end
    end

    describe "with invalid params" do
      it "assigns the tipomedalla as @tipomedalla" do
        tipomedalla = Tipomedalla.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tipomedalla.any_instance.stub(:save).and_return(false)
        put :update, {:id => tipomedalla.to_param, :tipomedalla => {}}, valid_session
        assigns(:tipomedalla).should eq(tipomedalla)
      end

      it "re-renders the 'edit' template" do
        tipomedalla = Tipomedalla.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tipomedalla.any_instance.stub(:save).and_return(false)
        put :update, {:id => tipomedalla.to_param, :tipomedalla => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tipomedalla" do
      tipomedalla = Tipomedalla.create! valid_attributes
      expect {
        delete :destroy, {:id => tipomedalla.to_param}, valid_session
      }.to change(Tipomedalla, :count).by(-1)
    end

    it "redirects to the tipomedallas list" do
      tipomedalla = Tipomedalla.create! valid_attributes
      delete :destroy, {:id => tipomedalla.to_param}, valid_session
      response.should redirect_to(tipomedallas_url)
    end
  end

end
